name: ci

on:
  push:
  pull_request:

jobs:
  node-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "web/package.json"
      - name: Syntax Check (Client)
        run: node --check web/scripts/app.js
      - name: Syntax Check (API)
        run: node --check web/api/v1/departures.js
      - name: Syntax Check (Client Error)
        run: node --check web/api/v1/client-error.js
      - name: Syntax Check (Digitransit)
        run: node --check web/api/lib/digitransit.js
      - name: Syntax Check (Utils)
        run: node --check web/api/lib/departures-utils.js
